# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07be9da37b3f4042c3894d727cd80ee2b5b69614bbfac6a668b657dc951fd0b378b9f211d36617572890f17180a7ab07a564aa026d8f6bda4273f44f0bd1788b

test:
  secret_key_base: 97b10ccd38d680e899460337966b25107ba4abc6927861a0c075a3611ff642ec5af9951e921c5b0bb0bec1c101adc098a6ece8e37af703d6ec040626f227fe9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
